// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SmartView.UIModule.PQA.TrendViewer.TrendViewerClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class TrendViewer
    {
        
        #region Properties
        public UISmartViewProductionQWindow UISmartViewProductionQWindow
        {
            get
            {
                if ((this.mUISmartViewProductionQWindow == null))
                {
                    this.mUISmartViewProductionQWindow = new UISmartViewProductionQWindow();
                }
                return this.mUISmartViewProductionQWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISmartViewProductionQWindow mUISmartViewProductionQWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartViewProductionQWindow : WinWindow
    {
        
        public UISmartViewProductionQWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartView Production Quality Advisor";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public UIToolbarMainWindow UIToolbarMainWindow
        {
            get
            {
                if ((this.mUIToolbarMainWindow == null))
                {
                    this.mUIToolbarMainWindow = new UIToolbarMainWindow(this);
                }
                return this.mUIToolbarMainWindow;
            }
        }
        
        public UITrendViewerWindow UITrendViewerWindow
        {
            get
            {
                if ((this.mUITrendViewerWindow == null))
                {
                    this.mUITrendViewerWindow = new UITrendViewerWindow(this);
                }
                return this.mUITrendViewerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIToolbarMainWindow mUIToolbarMainWindow;
        
        private UITrendViewerWindow mUITrendViewerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIToolbarMainWindow : WinWindow
    {
        
        public UIToolbarMainWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "toolbarMain";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinButton UITrendViewerButton
        {
            get
            {
                if ((this.mUITrendViewerButton == null))
                {
                    this.mUITrendViewerButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITrendViewerButton.SearchProperties[WinButton.PropertyNames.Name] = "Trend Viewer";
                    this.mUITrendViewerButton.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUITrendViewerButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITrendViewerButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITrendViewerWindow : WinWindow
    {
        
        public UITrendViewerWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TrendingForm";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UITrendViewerTitleBar
        {
            get
            {
                if ((this.mUITrendViewerTitleBar == null))
                {
                    this.mUITrendViewerTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUITrendViewerTitleBar.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUITrendViewerTitleBar;
            }
        }
        
        public UIToolbarWindow UIToolbarWindow
        {
            get
            {
                if ((this.mUIToolbarWindow == null))
                {
                    this.mUIToolbarWindow = new UIToolbarWindow(this);
                }
                return this.mUIToolbarWindow;
            }
        }
        
        public UIListboxWindow UIListboxWindow
        {
            get
            {
                if ((this.mUIListboxWindow == null))
                {
                    this.mUIListboxWindow = new UIListboxWindow(this);
                }
                return this.mUIListboxWindow;
            }
        }
        
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUITrendViewerTitleBar;
        
        private UIToolbarWindow mUIToolbarWindow;
        
        private UIListboxWindow mUIListboxWindow;
        
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIToolbarWindow : WinWindow
    {
        
        public UIToolbarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "toolbar";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Instance] = "4";
                    this.mUIItemButton.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIListboxWindow : WinWindow
    {
        
        public UIListboxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "listbox";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinList UIListboxList
        {
            get
            {
                if ((this.mUIListboxList == null))
                {
                    this.mUIListboxList = new WinList(this);
                    #region Search Criteria
                    this.mUIListboxList.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUIListboxList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIListboxList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIItemMenuItem
        {
            get
            {
                if ((this.mUIItemMenuItem == null))
                {
                    this.mUIItemMenuItem = new WinMenuItem(this);
                }
                return this.mUIItemMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIItemMenuItem;
        #endregion
    }
}
