// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SmartView.UIModule.Recipe.SheetQualityAnalysis.SheetQualityAnalysisClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class SheetQualityAnalysis
    {
        
        #region Properties
        public UISmartViewRecipeManagWindow UISmartViewRecipeManagWindow
        {
            get
            {
                if ((this.mUISmartViewRecipeManagWindow == null))
                {
                    this.mUISmartViewRecipeManagWindow = new UISmartViewRecipeManagWindow();
                }
                return this.mUISmartViewRecipeManagWindow;
            }
        }
        
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UISQAConfigurationWindow UISQAConfigurationWindow
        {
            get
            {
                if ((this.mUISQAConfigurationWindow == null))
                {
                    this.mUISQAConfigurationWindow = new UISQAConfigurationWindow();
                }
                return this.mUISQAConfigurationWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISmartViewRecipeManagWindow mUISmartViewRecipeManagWindow;
        
        private UIItemWindow2 mUIItemWindow;
        
        private UISQAConfigurationWindow mUISQAConfigurationWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartViewRecipeManagWindow : WinWindow
    {
        
        public UISmartViewRecipeManagWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartView Recipe Manager - test";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6MDIForm";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UISheetQualityAnalysisWindow UISheetQualityAnalysisWindow
        {
            get
            {
                if ((this.mUISheetQualityAnalysisWindow == null))
                {
                    this.mUISheetQualityAnalysisWindow = new UISheetQualityAnalysisWindow(this);
                }
                return this.mUISheetQualityAnalysisWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UISheetQualityAnalysisWindow mUISheetQualityAnalysisWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TreeViewWndClass";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public UIItemTree UIItemTree
        {
            get
            {
                if ((this.mUIItemTree == null))
                {
                    this.mUIItemTree = new UIItemTree(this);
                }
                return this.mUIItemTree;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTree mUIItemTree;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemTree : WinTree
    {
        
        public UIItemTree(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public UILineTreeItem UILineTreeItem
        {
            get
            {
                if ((this.mUILineTreeItem == null))
                {
                    this.mUILineTreeItem = new UILineTreeItem(this);
                }
                return this.mUILineTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UILineTreeItem mUILineTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UILineTreeItem : WinTreeItem
    {
        
        public UILineTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Line";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public UIStationTreeItem UIStationTreeItem
        {
            get
            {
                if ((this.mUIStationTreeItem == null))
                {
                    this.mUIStationTreeItem = new UIStationTreeItem(this);
                }
                return this.mUIStationTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIStationTreeItem mUIStationTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIStationTreeItem : WinTreeItem
    {
        
        public UIStationTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Station";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIView1TreeItem
        {
            get
            {
                if ((this.mUIView1TreeItem == null))
                {
                    this.mUIView1TreeItem = new WinTreeItem(this);
                    #region Search Criteria
                    this.mUIView1TreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "View 1";
                    this.mUIView1TreeItem.SearchProperties["Value"] = "2";
                    this.mUIView1TreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIView1TreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIView1TreeItem.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIView1TreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIView1TreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISheetQualityAnalysisWindow : WinWindow
    {
        
        public UISheetQualityAnalysisWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "32768";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public UIEnablesheetqualityanWindow UIEnablesheetqualityanWindow
        {
            get
            {
                if ((this.mUIEnablesheetqualityanWindow == null))
                {
                    this.mUIEnablesheetqualityanWindow = new UIEnablesheetqualityanWindow(this);
                }
                return this.mUIEnablesheetqualityanWindow;
            }
        }
        
        public UIItem0Window UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new UIItem0Window(this);
                }
                return this.mUIItem0Window;
            }
        }
        
        public UIImageparametersGroup UIImageparametersGroup
        {
            get
            {
                if ((this.mUIImageparametersGroup == null))
                {
                    this.mUIImageparametersGroup = new UIImageparametersGroup(this);
                }
                return this.mUIImageparametersGroup;
            }
        }
        
        public UIImageparametersWindow UIImageparametersWindow
        {
            get
            {
                if ((this.mUIImageparametersWindow == null))
                {
                    this.mUIImageparametersWindow = new UIImageparametersWindow(this);
                }
                return this.mUIImageparametersWindow;
            }
        }
        
        public UIItem0Window1 UIItem0Window1
        {
            get
            {
                if ((this.mUIItem0Window1 == null))
                {
                    this.mUIItem0Window1 = new UIItem0Window1(this);
                }
                return this.mUIItem0Window1;
            }
        }
        
        public UIItem0Window2 UIItem0Window2
        {
            get
            {
                if ((this.mUIItem0Window2 == null))
                {
                    this.mUIItem0Window2 = new UIItem0Window2(this);
                }
                return this.mUIItem0Window2;
            }
        }
        
        public UIItem0Window3 UIItem0Window3
        {
            get
            {
                if ((this.mUIItem0Window3 == null))
                {
                    this.mUIItem0Window3 = new UIItem0Window3(this);
                }
                return this.mUIItem0Window3;
            }
        }
        
        public UIMinimumdistancefromlWindow UIMinimumdistancefromlWindow
        {
            get
            {
                if ((this.mUIMinimumdistancefromlWindow == null))
                {
                    this.mUIMinimumdistancefromlWindow = new UIMinimumdistancefromlWindow(this);
                }
                return this.mUIMinimumdistancefromlWindow;
            }
        }
        
        public UIItem0Window4 UIItem0Window4
        {
            get
            {
                if ((this.mUIItem0Window4 == null))
                {
                    this.mUIItem0Window4 = new UIItem0Window4(this);
                }
                return this.mUIItem0Window4;
            }
        }
        
        public UIMinimumdistancefromrWindow UIMinimumdistancefromrWindow
        {
            get
            {
                if ((this.mUIMinimumdistancefromrWindow == null))
                {
                    this.mUIMinimumdistancefromrWindow = new UIMinimumdistancefromrWindow(this);
                }
                return this.mUIMinimumdistancefromrWindow;
            }
        }
        
        public UIItem0Window5 UIItem0Window5
        {
            get
            {
                if ((this.mUIItem0Window5 == null))
                {
                    this.mUIItem0Window5 = new UIItem0Window5(this);
                }
                return this.mUIItem0Window5;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UICenteredatWindow UICenteredatWindow
        {
            get
            {
                if ((this.mUICenteredatWindow == null))
                {
                    this.mUICenteredatWindow = new UICenteredatWindow(this);
                }
                return this.mUICenteredatWindow;
            }
        }
        
        public UICenteredincameraWindow UICenteredincameraWindow
        {
            get
            {
                if ((this.mUICenteredincameraWindow == null))
                {
                    this.mUICenteredincameraWindow = new UICenteredincameraWindow(this);
                }
                return this.mUICenteredincameraWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow111 UIItemWindow11
        {
            get
            {
                if ((this.mUIItemWindow11 == null))
                {
                    this.mUIItemWindow11 = new UIItemWindow111(this);
                }
                return this.mUIItemWindow11;
            }
        }
        
        public UIItemWindow12 UIItemWindow12
        {
            get
            {
                if ((this.mUIItemWindow12 == null))
                {
                    this.mUIItemWindow12 = new UIItemWindow12(this);
                }
                return this.mUIItemWindow12;
            }
        }
        
        public UIApplyWindow UIApplyWindow
        {
            get
            {
                if ((this.mUIApplyWindow == null))
                {
                    this.mUIApplyWindow = new UIApplyWindow(this);
                }
                return this.mUIApplyWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEnablesheetqualityanWindow mUIEnablesheetqualityanWindow;
        
        private UIItem0Window mUIItem0Window;
        
        private UIImageparametersGroup mUIImageparametersGroup;
        
        private UIImageparametersWindow mUIImageparametersWindow;
        
        private UIItem0Window1 mUIItem0Window1;
        
        private UIItem0Window2 mUIItem0Window2;
        
        private UIItem0Window3 mUIItem0Window3;
        
        private UIMinimumdistancefromlWindow mUIMinimumdistancefromlWindow;
        
        private UIItem0Window4 mUIItem0Window4;
        
        private UIMinimumdistancefromrWindow mUIMinimumdistancefromrWindow;
        
        private UIItem0Window5 mUIItem0Window5;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UICenteredatWindow mUICenteredatWindow;
        
        private UICenteredincameraWindow mUICenteredincameraWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow111 mUIItemWindow11;
        
        private UIItemWindow12 mUIItemWindow12;
        
        private UIApplyWindow mUIApplyWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIEnablesheetqualityanWindow : WinWindow
    {
        
        public UIEnablesheetqualityanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIEnablesheetqualityanCheckBox
        {
            get
            {
                if ((this.mUIEnablesheetqualityanCheckBox == null))
                {
                    this.mUIEnablesheetqualityanCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIEnablesheetqualityanCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Enable sheet quality analysis";
                    this.mUIEnablesheetqualityanCheckBox.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIEnablesheetqualityanCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIEnablesheetqualityanCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window : WinWindow
    {
        
        public UIItem0Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "9";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIImageparametersGroup : WinGroup
    {
        
        public UIImageparametersGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Image parameters";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Name] = "0";
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6TextBox";
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
                    this.mUIItem0Window.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItem0Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem0Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIImageparametersWindow : WinWindow
    {
        
        public UIImageparametersWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinGroup UIImageparametersGroup
        {
            get
            {
                if ((this.mUIImageparametersGroup == null))
                {
                    this.mUIImageparametersGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIImageparametersGroup.SearchProperties[WinControl.PropertyNames.Name] = "Image parameters";
                    this.mUIImageparametersGroup.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIImageparametersGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIImageparametersGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window1 : WinWindow
    {
        
        public UIItem0Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "10";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window2 : WinWindow
    {
        
        public UIItem0Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "8";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window3 : WinWindow
    {
        
        public UIItem0Window3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMinimumdistancefromlWindow : WinWindow
    {
        
        public UIMinimumdistancefromlWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "11";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIMinimumdistancefromlCheckBox
        {
            get
            {
                if ((this.mUIMinimumdistancefromlCheckBox == null))
                {
                    this.mUIMinimumdistancefromlCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIMinimumdistancefromlCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Minimum distance from left edge:";
                    this.mUIMinimumdistancefromlCheckBox.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIMinimumdistancefromlCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIMinimumdistancefromlCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window4 : WinWindow
    {
        
        public UIItem0Window4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "12";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMinimumdistancefromrWindow : WinWindow
    {
        
        public UIMinimumdistancefromrWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "13";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIMinimumdistancefromrCheckBox
        {
            get
            {
                if ((this.mUIMinimumdistancefromrCheckBox == null))
                {
                    this.mUIMinimumdistancefromrCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIMinimumdistancefromrCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Minimum distance from right edge:";
                    this.mUIMinimumdistancefromrCheckBox.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIMinimumdistancefromrCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIMinimumdistancefromrCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem0Window5 : WinWindow
    {
        
        public UIItem0Window5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "14";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ListView20WndClass";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinClient UIImageparametersClient
        {
            get
            {
                if ((this.mUIImageparametersClient == null))
                {
                    this.mUIImageparametersClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIImageparametersClient.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIImageparametersClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIImageparametersClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICenteredatWindow : WinWindow
    {
        
        public UICenteredatWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UICenteredatRadioButton
        {
            get
            {
                if ((this.mUICenteredatRadioButton == null))
                {
                    this.mUICenteredatRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUICenteredatRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Centered at ";
                    this.mUICenteredatRadioButton.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUICenteredatRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUICenteredatRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICenteredincameraWindow : WinWindow
    {
        
        public UICenteredincameraWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "4";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UICenteredincameraRadioButton
        {
            get
            {
                if ((this.mUICenteredincameraRadioButton == null))
                {
                    this.mUICenteredincameraRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUICenteredincameraRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Centered in camera";
                    this.mUICenteredincameraRadioButton.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUICenteredincameraRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUICenteredincameraRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "17";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow111 : WinWindow
    {
        
        public UIItemWindow111(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSFlexGridWndClass";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinClient UIAnalysismethodsClient
        {
            get
            {
                if ((this.mUIAnalysismethodsClient == null))
                {
                    this.mUIAnalysismethodsClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIAnalysismethodsClient.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIAnalysismethodsClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIAnalysismethodsClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow12 : WinWindow
    {
        
        public UIItemWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSFlexGridWndClass";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinClient UIAnalysismethodsClient
        {
            get
            {
                if ((this.mUIAnalysismethodsClient == null))
                {
                    this.mUIAnalysismethodsClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIAnalysismethodsClient.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIAnalysismethodsClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIAnalysismethodsClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIApplyWindow : WinWindow
    {
        
        public UIApplyWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "16";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinButton UIApplyButton
        {
            get
            {
                if ((this.mUIApplyButton == null))
                {
                    this.mUIApplyButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIApplyButton.SearchProperties[WinButton.PropertyNames.Name] = "Apply";
                    this.mUIApplyButton.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIApplyButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIApplyButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "19";
            this.WindowTitles.Add("SmartView Recipe Manager - test");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("SmartView Recipe Manager - test");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UISheetQualityAnalysisMenuItem
        {
            get
            {
                if ((this.mUISheetQualityAnalysisMenuItem == null))
                {
                    this.mUISheetQualityAnalysisMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISheetQualityAnalysisMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Sheet Quality Analysis...";
                    #endregion
                }
                return this.mUISheetQualityAnalysisMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUISheetQualityAnalysisMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISQAConfigurationWindow : WinWindow
    {
        
        public UISQAConfigurationWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SQA Configuration";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("SQA Configuration");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIOpenWindow UIOpenWindow
        {
            get
            {
                if ((this.mUIOpenWindow == null))
                {
                    this.mUIOpenWindow = new UIOpenWindow(this);
                }
                return this.mUIOpenWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIOpenWindow mUIOpenWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1148";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("SQA Configuration");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIFilenameComboBox
        {
            get
            {
                if ((this.mUIFilenameComboBox == null))
                {
                    this.mUIFilenameComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIFilenameComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "File name:";
                    this.mUIFilenameComboBox.WindowTitles.Add("SQA Configuration");
                    #endregion
                }
                return this.mUIFilenameComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIFilenameComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOpenWindow : WinWindow
    {
        
        public UIOpenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("SQA Configuration");
            #endregion
        }
        
        #region Properties
        public WinSplitButton UIOpenSplitButton
        {
            get
            {
                if ((this.mUIOpenSplitButton == null))
                {
                    this.mUIOpenSplitButton = new WinSplitButton(this);
                    #region Search Criteria
                    this.mUIOpenSplitButton.SearchProperties[WinButton.PropertyNames.Name] = "Open";
                    this.mUIOpenSplitButton.WindowTitles.Add("SQA Configuration");
                    #endregion
                }
                return this.mUIOpenSplitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinSplitButton mUIOpenSplitButton;
        #endregion
    }
}
