// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SmartView.UIModule.PQA.WebViewer.WebViewerToolsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class WebViewerTools
    {
        
        #region Properties
        public UISmartViewProductionQWindow UISmartViewProductionQWindow
        {
            get
            {
                if ((this.mUISmartViewProductionQWindow == null))
                {
                    this.mUISmartViewProductionQWindow = new UISmartViewProductionQWindow();
                }
                return this.mUISmartViewProductionQWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIDisplayOptionsWindow UIDisplayOptionsWindow
        {
            get
            {
                if ((this.mUIDisplayOptionsWindow == null))
                {
                    this.mUIDisplayOptionsWindow = new UIDisplayOptionsWindow();
                }
                return this.mUIDisplayOptionsWindow;
            }
        }
        
        public UISideLabelsWindow UISideLabelsWindow
        {
            get
            {
                if ((this.mUISideLabelsWindow == null))
                {
                    this.mUISideLabelsWindow = new UISideLabelsWindow();
                }
                return this.mUISideLabelsWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISmartViewProductionQWindow mUISmartViewProductionQWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIDisplayOptionsWindow mUIDisplayOptionsWindow;
        
        private UISideLabelsWindow mUISideLabelsWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartViewProductionQWindow : WinWindow
    {
        
        public UISmartViewProductionQWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartView Production Quality Advisor";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public UICcm6015RC731Window UICcm6015RC731Window
        {
            get
            {
                if ((this.mUICcm6015RC731Window == null))
                {
                    this.mUICcm6015RC731Window = new UICcm6015RC731Window(this);
                }
                return this.mUICcm6015RC731Window;
            }
        }
        
        public UIDefaultClient UIDefaultClient
        {
            get
            {
                if ((this.mUIDefaultClient == null))
                {
                    this.mUIDefaultClient = new UIDefaultClient(this);
                }
                return this.mUIDefaultClient;
            }
        }
        #endregion
        
        #region Fields
        private UICcm6015RC731Window mUICcm6015RC731Window;
        
        private UIDefaultClient mUIDefaultClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICcm6015RC731Window : WinWindow
    {
        
        public UICcm6015RC731Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "FullWebViewerForm";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public UICcm6015RC731Client UICcm6015RC731Client
        {
            get
            {
                if ((this.mUICcm6015RC731Client == null))
                {
                    this.mUICcm6015RC731Client = new UICcm6015RC731Client(this);
                }
                return this.mUICcm6015RC731Client;
            }
        }
        
        public WinClient UIX4Client
        {
            get
            {
                if ((this.mUIX4Client == null))
                {
                    this.mUIX4Client = new WinClient(this);
                    #region Search Criteria
                    this.mUIX4Client.SearchProperties[WinControl.PropertyNames.Name] = "x-4";
                    this.mUIX4Client.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUIX4Client;
            }
        }
        #endregion
        
        #region Fields
        private UICcm6015RC731Client mUICcm6015RC731Client;
        
        private WinClient mUIX4Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICcm6015RC731Client : WinClient
    {
        
        public UICcm6015RC731Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "ccm-6015RC7-31";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinWindow UIViewportWindow
        {
            get
            {
                if ((this.mUIViewportWindow == null))
                {
                    this.mUIViewportWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIViewportWindow.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6UserControlDC";
                    this.mUIViewportWindow.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUIViewportWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIViewportWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDefaultClient : WinClient
    {
        
        public UIDefaultClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Workspace";
            this.WindowTitles.Add("SmartView Production Quality Advisor");
            #endregion
        }
        
        #region Properties
        public WinWindow UIX4Window
        {
            get
            {
                if ((this.mUIX4Window == null))
                {
                    this.mUIX4Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIX4Window.SearchProperties[WinWindow.PropertyNames.Name] = "x-4";
                    this.mUIX4Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIX4Window.WindowTitles.Add("SmartView Production Quality Advisor");
                    #endregion
                }
                return this.mUIX4Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIX4Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DDFLT";
            #endregion
        }
        
        #region Properties
        public WinClient UIDesktopClient
        {
            get
            {
                if ((this.mUIDesktopClient == null))
                {
                    this.mUIDesktopClient = new WinClient(this);
                }
                return this.mUIDesktopClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDesktopClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDisplayOptionsWindow : WinWindow
    {
        
        public UIDisplayOptionsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Display Options";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Display Options");
            #endregion
        }
        
        #region Properties
        public UISidelabelsWindow UISidelabelsWindow
        {
            get
            {
                if ((this.mUISidelabelsWindow == null))
                {
                    this.mUISidelabelsWindow = new UISidelabelsWindow(this);
                }
                return this.mUISidelabelsWindow;
            }
        }
        
        public UIDisplayOptionsTitleBar UIDisplayOptionsTitleBar
        {
            get
            {
                if ((this.mUIDisplayOptionsTitleBar == null))
                {
                    this.mUIDisplayOptionsTitleBar = new UIDisplayOptionsTitleBar(this);
                }
                return this.mUIDisplayOptionsTitleBar;
            }
        }
        
        public UIDefectlabelsWindow UIDefectlabelsWindow
        {
            get
            {
                if ((this.mUIDefectlabelsWindow == null))
                {
                    this.mUIDefectlabelsWindow = new UIDefectlabelsWindow(this);
                }
                return this.mUIDefectlabelsWindow;
            }
        }
        
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISidelabelsWindow mUISidelabelsWindow;
        
        private UIDisplayOptionsTitleBar mUIDisplayOptionsTitleBar;
        
        private UIDefectlabelsWindow mUIDefectlabelsWindow;
        
        private UIItemWindow2 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISidelabelsWindow : WinWindow
    {
        
        public UISidelabelsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "17";
            this.WindowTitles.Add("Display Options");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UISidelabelsCheckBox
        {
            get
            {
                if ((this.mUISidelabelsCheckBox == null))
                {
                    this.mUISidelabelsCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUISidelabelsCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Side labels";
                    this.mUISidelabelsCheckBox.WindowTitles.Add("Display Options");
                    #endregion
                }
                return this.mUISidelabelsCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUISidelabelsCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDisplayOptionsTitleBar : WinTitleBar
    {
        
        public UIDisplayOptionsTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Display Options");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Display Options");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDefectlabelsWindow : WinWindow
    {
        
        public UIDefectlabelsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "22";
            this.WindowTitles.Add("Display Options");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIDefectlabelsCheckBox
        {
            get
            {
                if ((this.mUIDefectlabelsCheckBox == null))
                {
                    this.mUIDefectlabelsCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIDefectlabelsCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Defect labels";
                    this.mUIDefectlabelsCheckBox.WindowTitles.Add("Display Options");
                    #endregion
                }
                return this.mUIDefectlabelsCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIDefectlabelsCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "23";
            this.WindowTitles.Add("Display Options");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Display Options");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISideLabelsWindow : WinWindow
    {
        
        public UISideLabelsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Side Labels";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Side Labels");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSFlexGridWndClass";
            this.WindowTitles.Add("Side Labels");
            #endregion
        }
        
        #region Properties
        public WinClient UISideLabelsClient
        {
            get
            {
                if ((this.mUISideLabelsClient == null))
                {
                    this.mUISideLabelsClient = new WinClient(this);
                    #region Search Criteria
                    this.mUISideLabelsClient.WindowTitles.Add("Side Labels");
                    #endregion
                }
                return this.mUISideLabelsClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUISideLabelsClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5";
            this.WindowTitles.Add("Side Labels");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Side Labels");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "3";
            this.WindowTitles.Add("Side Labels");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Side Labels");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
