// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SmartView.UIModule.ClassifierMgr.ClassifierManagerClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class ClassifierManager
    {
        
        /// <summary>
        /// SaveClassifier - Use 'SaveClassifierParams' to pass parameters into this method.
        /// </summary>
        public void SaveClassifier(String name)
        {
            #region Variable Declarations
            WinMenuItem uISaveAsMenuItem = this.UISmartLearnClassifierWindow.UIMainFormMenuBar.UIFileMenuItem.UISaveAsMenuItem;
            WinEdit uITextNameEdit = this.UISaveClassifierWindow.UITextNameWindow.UITextNameEdit;
            WinButton uISaveButton = this.UISaveClassifierWindow.UISaveWindow.UISaveButton;
            #endregion

            // Click 'File' -> 'Save As...' menu item
            Mouse.Click(uISaveAsMenuItem, new Point(69, 12));

            // Type 'Automation' in 'textName' text box
            uITextNameEdit.Text = name;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(45, 20));
        }
        
        /// <summary>
        /// CloseClassifierManager
        /// </summary>
        
        
        /// <summary>
        /// DeleteClassfier - Use 'DeleteClassfierParams' to pass parameters into this method.
        /// </summary>
        public void DeleteClassfier()
        {
            #region Variable Declarations
            WinMenuItem uIDeleteMenuItem = this.UISmartLearnClassifierWindow.UIMainFormMenuBar.UIFileMenuItem.UIDeleteMenuItem;
            WinEdit uITextNameEdit = this.UIDeleteClassifierWindow.UITextNameWindow.UITextNameEdit;
            WinButton uIDeleteButton = this.UIDeleteClassifierWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIYesButton = this.UIDeleteClassifierWindow1.UIYesWindow.UIYesButton;
            #endregion

            // Click 'File' -> 'Delete...' menu item
            Mouse.Click(uIDeleteMenuItem, new Point(52, 14));

            // Type 'Automation' in 'textName' text box
            uITextNameEdit.Text = this.DeleteClassfierParams.UITextNameEditText;

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(34, 15));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(22, 13));
        }
        
        #region Properties
        public virtual SaveClassifierParams SaveClassifierParams
        {
            get
            {
                if ((this.mSaveClassifierParams == null))
                {
                    this.mSaveClassifierParams = new SaveClassifierParams();
                }
                return this.mSaveClassifierParams;
            }
        }
        
        public virtual DeleteClassfierParams DeleteClassfierParams
        {
            get
            {
                if ((this.mDeleteClassfierParams == null))
                {
                    this.mDeleteClassfierParams = new DeleteClassfierParams();
                }
                return this.mDeleteClassfierParams;
            }
        }
        
        public UISmartLearnClassifierWindow UISmartLearnClassifierWindow
        {
            get
            {
                if ((this.mUISmartLearnClassifierWindow == null))
                {
                    this.mUISmartLearnClassifierWindow = new UISmartLearnClassifierWindow();
                }
                return this.mUISmartLearnClassifierWindow;
            }
        }
        
        public UINewClassifierWindow UINewClassifierWindow
        {
            get
            {
                if ((this.mUINewClassifierWindow == null))
                {
                    this.mUINewClassifierWindow = new UINewClassifierWindow();
                }
                return this.mUINewClassifierWindow;
            }
        }
        
        public UISaveClassifierWindow UISaveClassifierWindow
        {
            get
            {
                if ((this.mUISaveClassifierWindow == null))
                {
                    this.mUISaveClassifierWindow = new UISaveClassifierWindow();
                }
                return this.mUISaveClassifierWindow;
            }
        }
        
        public UISmartLearnClassifierWindow1 UISmartLearnClassifierWindow1
        {
            get
            {
                if ((this.mUISmartLearnClassifierWindow1 == null))
                {
                    this.mUISmartLearnClassifierWindow1 = new UISmartLearnClassifierWindow1();
                }
                return this.mUISmartLearnClassifierWindow1;
            }
        }
        
        public UIDeleteClassifierWindow UIDeleteClassifierWindow
        {
            get
            {
                if ((this.mUIDeleteClassifierWindow == null))
                {
                    this.mUIDeleteClassifierWindow = new UIDeleteClassifierWindow();
                }
                return this.mUIDeleteClassifierWindow;
            }
        }
        
        public UIDeleteClassifierWindow1 UIDeleteClassifierWindow1
        {
            get
            {
                if ((this.mUIDeleteClassifierWindow1 == null))
                {
                    this.mUIDeleteClassifierWindow1 = new UIDeleteClassifierWindow1();
                }
                return this.mUIDeleteClassifierWindow1;
            }
        }
        #endregion
        
        #region Fields
        private SaveClassifierParams mSaveClassifierParams;
        
        private DeleteClassfierParams mDeleteClassfierParams;
        
        private UISmartLearnClassifierWindow mUISmartLearnClassifierWindow;
        
        private UINewClassifierWindow mUINewClassifierWindow;
        
        private UISaveClassifierWindow mUISaveClassifierWindow;
        
        private UISmartLearnClassifierWindow1 mUISmartLearnClassifierWindow1;
        
        private UIDeleteClassifierWindow mUIDeleteClassifierWindow;
        
        private UIDeleteClassifierWindow1 mUIDeleteClassifierWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SaveClassifier'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class SaveClassifierParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Automation' in 'textName' text box
        /// </summary>
        public string UITextNameEditText = "Automation";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DeleteClassfier'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class DeleteClassfierParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Automation' in 'textName' text box
        /// </summary>
        public string UITextNameEditText = "Automation";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartLearnClassifierWindow : WinWindow
    {
        
        public UISmartLearnClassifierWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartLearn Classifier Manager";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SmartLearn Classifier Manager");
            #endregion
        }
        
        #region Properties
        public UIMainFormMenuBar UIMainFormMenuBar
        {
            get
            {
                if ((this.mUIMainFormMenuBar == null))
                {
                    this.mUIMainFormMenuBar = new UIMainFormMenuBar(this);
                }
                return this.mUIMainFormMenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMainFormMenuBar mUIMainFormMenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMainFormMenuBar : WinMenuBar
    {
        
        public UIMainFormMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Application";
            this.WindowTitles.Add("SmartLearn Classifier Manager");
            #endregion
        }
        
        #region Properties
        public UIFileMenuItem UIFileMenuItem
        {
            get
            {
                if ((this.mUIFileMenuItem == null))
                {
                    this.mUIFileMenuItem = new UIFileMenuItem(this);
                }
                return this.mUIFileMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIFileMenuItem mUIFileMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFileMenuItem : WinMenuItem
    {
        
        public UIFileMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "File";
            this.WindowTitles.Add("SmartLearn Classifier Manager");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UINewCtrlNMenuItem
        {
            get
            {
                if ((this.mUINewCtrlNMenuItem == null))
                {
                    this.mUINewCtrlNMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUINewCtrlNMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "New...\tCtrl+N";
                    this.mUINewCtrlNMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUINewCtrlNMenuItem.WindowTitles.Add("SmartLearn Classifier Manager");
                    #endregion
                }
                return this.mUINewCtrlNMenuItem;
            }
        }
        
        public WinMenuItem UISaveAsMenuItem
        {
            get
            {
                if ((this.mUISaveAsMenuItem == null))
                {
                    this.mUISaveAsMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISaveAsMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Save As...";
                    this.mUISaveAsMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUISaveAsMenuItem.WindowTitles.Add("SmartLearn Classifier Manager");
                    #endregion
                }
                return this.mUISaveAsMenuItem;
            }
        }
        
        public WinMenuItem UIDeleteMenuItem
        {
            get
            {
                if ((this.mUIDeleteMenuItem == null))
                {
                    this.mUIDeleteMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIDeleteMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Delete...";
                    this.mUIDeleteMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIDeleteMenuItem.WindowTitles.Add("SmartLearn Classifier Manager");
                    #endregion
                }
                return this.mUIDeleteMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUINewCtrlNMenuItem;
        
        private WinMenuItem mUISaveAsMenuItem;
        
        private WinMenuItem mUIDeleteMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UINewClassifierWindow : WinWindow
    {
        
        public UINewClassifierWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "New Classifier";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public UISynchronizedWindow UISynchronizedWindow
        {
            get
            {
                if ((this.mUISynchronizedWindow == null))
                {
                    this.mUISynchronizedWindow = new UISynchronizedWindow(this);
                }
                return this.mUISynchronizedWindow;
            }
        }
        
        public UIMarkreaderWindow UIMarkreaderWindow
        {
            get
            {
                if ((this.mUIMarkreaderWindow == null))
                {
                    this.mUIMarkreaderWindow = new UIMarkreaderWindow(this);
                }
                return this.mUIMarkreaderWindow;
            }
        }
        
        public UIStandardWindow UIStandardWindow
        {
            get
            {
                if ((this.mUIStandardWindow == null))
                {
                    this.mUIStandardWindow = new UIStandardWindow(this);
                }
                return this.mUIStandardWindow;
            }
        }
        
        public UISmartLearnmultistepWindow UISmartLearnmultistepWindow
        {
            get
            {
                if ((this.mUISmartLearnmultistepWindow == null))
                {
                    this.mUISmartLearnmultistepWindow = new UISmartLearnmultistepWindow(this);
                }
                return this.mUISmartLearnmultistepWindow;
            }
        }
        
        public UIListEnginesWindow UIListEnginesWindow
        {
            get
            {
                if ((this.mUIListEnginesWindow == null))
                {
                    this.mUIListEnginesWindow = new UIListEnginesWindow(this);
                }
                return this.mUIListEnginesWindow;
            }
        }
        
        public UIUsedefaultparametersWindow UIUsedefaultparametersWindow
        {
            get
            {
                if ((this.mUIUsedefaultparametersWindow == null))
                {
                    this.mUIUsedefaultparametersWindow = new UIUsedefaultparametersWindow(this);
                }
                return this.mUIUsedefaultparametersWindow;
            }
        }
        
        public UISmartViewstandardWindow UISmartViewstandardWindow
        {
            get
            {
                if ((this.mUISmartViewstandardWindow == null))
                {
                    this.mUISmartViewstandardWindow = new UISmartViewstandardWindow(this);
                }
                return this.mUISmartViewstandardWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISynchronizedWindow mUISynchronizedWindow;
        
        private UIMarkreaderWindow mUIMarkreaderWindow;
        
        private UIStandardWindow mUIStandardWindow;
        
        private UISmartLearnmultistepWindow mUISmartLearnmultistepWindow;
        
        private UIListEnginesWindow mUIListEnginesWindow;
        
        private UIUsedefaultparametersWindow mUIUsedefaultparametersWindow;
        
        private UISmartViewstandardWindow mUISmartViewstandardWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISynchronizedWindow : WinWindow
    {
        
        public UISynchronizedWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnViewSynchronized";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UISynchronizedRadioButton
        {
            get
            {
                if ((this.mUISynchronizedRadioButton == null))
                {
                    this.mUISynchronizedRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUISynchronizedRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Synchronized";
                    this.mUISynchronizedRadioButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUISynchronizedRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUISynchronizedRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMarkreaderWindow : WinWindow
    {
        
        public UIMarkreaderWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnViewWinder";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIMarkreaderRadioButton
        {
            get
            {
                if ((this.mUIMarkreaderRadioButton == null))
                {
                    this.mUIMarkreaderRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIMarkreaderRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Mark reader";
                    this.mUIMarkreaderRadioButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUIMarkreaderRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIMarkreaderRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIStandardWindow : WinWindow
    {
        
        public UIStandardWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnViewStandard";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIStandardRadioButton
        {
            get
            {
                if ((this.mUIStandardRadioButton == null))
                {
                    this.mUIStandardRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIStandardRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Standard";
                    this.mUIStandardRadioButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUIStandardRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIStandardRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartLearnmultistepWindow : WinWindow
    {
        
        public UISmartLearnmultistepWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnSmartLearn";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UISmartLearnmultistepRadioButton
        {
            get
            {
                if ((this.mUISmartLearnmultistepRadioButton == null))
                {
                    this.mUISmartLearnmultistepRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUISmartLearnmultistepRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "SmartLearn (multi-step)";
                    this.mUISmartLearnmultistepRadioButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUISmartLearnmultistepRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUISmartLearnmultistepRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIListEnginesWindow : WinWindow
    {
        
        public UIListEnginesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "listEngines";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinList UIListEnginesList
        {
            get
            {
                if ((this.mUIListEnginesList == null))
                {
                    this.mUIListEnginesList = new WinList(this);
                    #region Search Criteria
                    this.mUIListEnginesList.SearchProperties[WinList.PropertyNames.Name] = "Engine";
                    this.mUIListEnginesList.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUIListEnginesList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIListEnginesList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIUsedefaultparametersWindow : WinWindow
    {
        
        public UIUsedefaultparametersWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "chkUseDefaults";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIUsedefaultparametersCheckBox
        {
            get
            {
                if ((this.mUIUsedefaultparametersCheckBox == null))
                {
                    this.mUIUsedefaultparametersCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIUsedefaultparametersCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Use default parameters";
                    this.mUIUsedefaultparametersCheckBox.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUIUsedefaultparametersCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIUsedefaultparametersCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartViewstandardWindow : WinWindow
    {
        
        public UISmartViewstandardWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnSmartView";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UISmartViewstandardRadioButton
        {
            get
            {
                if ((this.mUISmartViewstandardRadioButton == null))
                {
                    this.mUISmartViewstandardRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUISmartViewstandardRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "SmartView (standard)";
                    this.mUISmartViewstandardRadioButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUISmartViewstandardRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUISmartViewstandardRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnOK";
            this.WindowTitles.Add("New Classifier");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("New Classifier");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISaveClassifierWindow : WinWindow
    {
        
        public UISaveClassifierWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Save Classifier";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Save Classifier");
            #endregion
        }
        
        #region Properties
        public UITextNameWindow UITextNameWindow
        {
            get
            {
                if ((this.mUITextNameWindow == null))
                {
                    this.mUITextNameWindow = new UITextNameWindow(this);
                }
                return this.mUITextNameWindow;
            }
        }
        
        public UISaveWindow UISaveWindow
        {
            get
            {
                if ((this.mUISaveWindow == null))
                {
                    this.mUISaveWindow = new UISaveWindow(this);
                }
                return this.mUISaveWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITextNameWindow mUITextNameWindow;
        
        private UISaveWindow mUISaveWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITextNameWindow : WinWindow
    {
        
        public UITextNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textName";
            this.WindowTitles.Add("Save Classifier");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextNameEdit
        {
            get
            {
                if ((this.mUITextNameEdit == null))
                {
                    this.mUITextNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextNameEdit.WindowTitles.Add("Save Classifier");
                    #endregion
                }
                return this.mUITextNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISaveWindow : WinWindow
    {
        
        public UISaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnOK";
            this.WindowTitles.Add("Save Classifier");
            #endregion
        }
        
        #region Properties
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("Save Classifier");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartLearnClassifierWindow1 : WinWindow
    {
        
        public UISmartLearnClassifierWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartLearn Classifier Manager - [Automation]";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SmartLearn Classifier Manager - [Automation]");
            #endregion
        }
        
        #region Properties
        public UISmartLearnClassifierTitleBar UISmartLearnClassifierTitleBar
        {
            get
            {
                if ((this.mUISmartLearnClassifierTitleBar == null))
                {
                    this.mUISmartLearnClassifierTitleBar = new UISmartLearnClassifierTitleBar(this);
                }
                return this.mUISmartLearnClassifierTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UISmartLearnClassifierTitleBar mUISmartLearnClassifierTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartLearnClassifierTitleBar : WinTitleBar
    {
        
        public UISmartLearnClassifierTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("SmartLearn Classifier Manager - [Automation]");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("SmartLearn Classifier Manager - [Automation]");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteClassifierWindow : WinWindow
    {
        
        public UIDeleteClassifierWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Delete Classifier";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Delete Classifier");
            #endregion
        }
        
        #region Properties
        public UITextNameWindow1 UITextNameWindow
        {
            get
            {
                if ((this.mUITextNameWindow == null))
                {
                    this.mUITextNameWindow = new UITextNameWindow1(this);
                }
                return this.mUITextNameWindow;
            }
        }
        
        public UIDeleteWindow UIDeleteWindow
        {
            get
            {
                if ((this.mUIDeleteWindow == null))
                {
                    this.mUIDeleteWindow = new UIDeleteWindow(this);
                }
                return this.mUIDeleteWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITextNameWindow1 mUITextNameWindow;
        
        private UIDeleteWindow mUIDeleteWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITextNameWindow1 : WinWindow
    {
        
        public UITextNameWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textName";
            this.WindowTitles.Add("Delete Classifier");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextNameEdit
        {
            get
            {
                if ((this.mUITextNameEdit == null))
                {
                    this.mUITextNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextNameEdit.WindowTitles.Add("Delete Classifier");
                    #endregion
                }
                return this.mUITextNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteWindow : WinWindow
    {
        
        public UIDeleteWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnOK";
            this.WindowTitles.Add("Delete Classifier");
            #endregion
        }
        
        #region Properties
        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("Delete Classifier");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteClassifierWindow1 : WinWindow
    {
        
        public UIDeleteClassifierWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Delete Classifier";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Delete Classifier");
            #endregion
        }
        
        #region Properties
        public UIYesWindow UIYesWindow
        {
            get
            {
                if ((this.mUIYesWindow == null))
                {
                    this.mUIYesWindow = new UIYesWindow(this);
                }
                return this.mUIYesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYesWindow mUIYesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIYesWindow : WinWindow
    {
        
        public UIYesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Delete Classifier");
            #endregion
        }
        
        #region Properties
        public WinButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WinButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Delete Classifier");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIYesButton;
        #endregion
    }
}
