// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SVConsole.UIModule.Console.MultiDefectViewer.MDVToolsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class MDVTools
    {
        
        #region Properties
        public UISmartViewConsole4CamWindow UISmartViewConsole4CamWindow
        {
            get
            {
                if ((this.mUISmartViewConsole4CamWindow == null))
                {
                    this.mUISmartViewConsole4CamWindow = new UISmartViewConsole4CamWindow();
                }
                return this.mUISmartViewConsole4CamWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIGoToWindow UIGoToWindow
        {
            get
            {
                if ((this.mUIGoToWindow == null))
                {
                    this.mUIGoToWindow = new UIGoToWindow();
                }
                return this.mUIGoToWindow;
            }
        }
        
        public UIQueryDefinitionWindow UIQueryDefinitionWindow
        {
            get
            {
                if ((this.mUIQueryDefinitionWindow == null))
                {
                    this.mUIQueryDefinitionWindow = new UIQueryDefinitionWindow();
                }
                return this.mUIQueryDefinitionWindow;
            }
        }
        
        public UIItemWindow12 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow12();
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UILiveModeSettingsWindow UILiveModeSettingsWindow
        {
            get
            {
                if ((this.mUILiveModeSettingsWindow == null))
                {
                    this.mUILiveModeSettingsWindow = new UILiveModeSettingsWindow();
                }
                return this.mUILiveModeSettingsWindow;
            }
        }
        
        public UIFeatureSelectionWindow UIFeatureSelectionWindow
        {
            get
            {
                if ((this.mUIFeatureSelectionWindow == null))
                {
                    this.mUIFeatureSelectionWindow = new UIFeatureSelectionWindow();
                }
                return this.mUIFeatureSelectionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISmartViewConsole4CamWindow mUISmartViewConsole4CamWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIGoToWindow mUIGoToWindow;
        
        private UIQueryDefinitionWindow mUIQueryDefinitionWindow;
        
        private UIItemWindow12 mUIItemWindow1;
        
        private UILiveModeSettingsWindow mUILiveModeSettingsWindow;
        
        private UIFeatureSelectionWindow mUIFeatureSelectionWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISmartViewConsole4CamWindow : WinWindow
    {
        
        public UISmartViewConsole4CamWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SmartView Console: 4 Camera, Station";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6MDIForm";
            this.WindowTitles.Add("SmartView Console: 4 Camera, Station");
            #endregion
        }
        
        #region Properties
        public UIMultiDefectViewerWindow UIMultiDefectViewerWindow
        {
            get
            {
                if ((this.mUIMultiDefectViewerWindow == null))
                {
                    this.mUIMultiDefectViewerWindow = new UIMultiDefectViewerWindow(this);
                }
                return this.mUIMultiDefectViewerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMultiDefectViewerWindow mUIMultiDefectViewerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMultiDefectViewerWindow : WinWindow
    {
        
        public UIMultiDefectViewerWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "32770";
            this.WindowTitles.Add("SmartView Console: 4 Camera, Station");
            #endregion
        }
        
        #region Properties
        public UIMultiDefectViewerClient UIMultiDefectViewerClient
        {
            get
            {
                if ((this.mUIMultiDefectViewerClient == null))
                {
                    this.mUIMultiDefectViewerClient = new UIMultiDefectViewerClient(this);
                }
                return this.mUIMultiDefectViewerClient;
            }
        }
        #endregion
        
        #region Fields
        private UIMultiDefectViewerClient mUIMultiDefectViewerClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMultiDefectViewerClient : WinClient
    {
        
        public UIMultiDefectViewerClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Multi-Defect Viewer";
            this.WindowTitles.Add("SmartView Console: 4 Camera, Station");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItemWindow.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6UserControlDC";
                    this.mUIItemWindow.WindowTitles.Add("SmartView Console: 4 Camera, Station");
                    #endregion
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DDFLT";
            #endregion
        }
        
        #region Properties
        public WinClient UIDesktopClient
        {
            get
            {
                if ((this.mUIDesktopClient == null))
                {
                    this.mUIDesktopClient = new WinClient(this);
                }
                return this.mUIDesktopClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDesktopClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGoToWindow : WinWindow
    {
        
        public UIGoToWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Go To";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIText1Window UIText1Window
        {
            get
            {
                if ((this.mUIText1Window == null))
                {
                    this.mUIText1Window = new UIText1Window(this);
                }
                return this.mUIText1Window;
            }
        }
        
        public UIGOWindow UIGOWindow
        {
            get
            {
                if ((this.mUIGOWindow == null))
                {
                    this.mUIGOWindow = new UIGOWindow(this);
                }
                return this.mUIGOWindow;
            }
        }
        
        public UIText1Window1 UIText1Window1
        {
            get
            {
                if ((this.mUIText1Window1 == null))
                {
                    this.mUIText1Window1 = new UIText1Window1(this);
                }
                return this.mUIText1Window1;
            }
        }
        
        public UIGOWindow1 UIGOWindow1
        {
            get
            {
                if ((this.mUIGOWindow1 == null))
                {
                    this.mUIGOWindow1 = new UIGOWindow1(this);
                }
                return this.mUIGOWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        
        private UIText1Window mUIText1Window;
        
        private UIGOWindow mUIGOWindow;
        
        private UIText1Window1 mUIText1Window1;
        
        private UIGOWindow1 mUIGOWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public WinListItem UIView1ListItem
        {
            get
            {
                if ((this.mUIView1ListItem == null))
                {
                    this.mUIView1ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIView1ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "View 1";
                    this.mUIView1ListItem.WindowTitles.Add("Go To");
                    #endregion
                }
                return this.mUIView1ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIView1ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window : WinWindow
    {
        
        public UIText1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Go To");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGOWindow : WinWindow
    {
        
        public UIGOWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public WinButton UIGOButton
        {
            get
            {
                if ((this.mUIGOButton == null))
                {
                    this.mUIGOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGOButton.SearchProperties[WinButton.PropertyNames.Name] = "Go";
                    this.mUIGOButton.WindowTitles.Add("Go To");
                    #endregion
                }
                return this.mUIGOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGOButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window1 : WinWindow
    {
        
        public UIText1Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Go To");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGOWindow1 : WinWindow
    {
        
        public UIGOWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "3";
            this.WindowTitles.Add("Go To");
            #endregion
        }
        
        #region Properties
        public WinButton UIGOButton
        {
            get
            {
                if ((this.mUIGOButton == null))
                {
                    this.mUIGOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGOButton.SearchProperties[WinButton.PropertyNames.Name] = "Go";
                    this.mUIGOButton.WindowTitles.Add("Go To");
                    #endregion
                }
                return this.mUIGOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGOButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIQueryDefinitionWindow : WinWindow
    {
        
        public UIQueryDefinitionWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Query Definition";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public UIApplyqueryWindow UIApplyqueryWindow
        {
            get
            {
                if ((this.mUIApplyqueryWindow == null))
                {
                    this.mUIApplyqueryWindow = new UIApplyqueryWindow(this);
                }
                return this.mUIApplyqueryWindow;
            }
        }
        
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UISeverityWindow UISeverityWindow
        {
            get
            {
                if ((this.mUISeverityWindow == null))
                {
                    this.mUISeverityWindow = new UISeverityWindow(this);
                }
                return this.mUISeverityWindow;
            }
        }
        
        public UIText1Window2 UIText1Window
        {
            get
            {
                if ((this.mUIText1Window == null))
                {
                    this.mUIText1Window = new UIText1Window2(this);
                }
                return this.mUIText1Window;
            }
        }
        
        public UIAllWindow UIAllWindow
        {
            get
            {
                if ((this.mUIAllWindow == null))
                {
                    this.mUIAllWindow = new UIAllWindow(this);
                }
                return this.mUIAllWindow;
            }
        }
        
        public UISelectedclassesWindow UISelectedclassesWindow
        {
            get
            {
                if ((this.mUISelectedclassesWindow == null))
                {
                    this.mUISelectedclassesWindow = new UISelectedclassesWindow(this);
                }
                return this.mUISelectedclassesWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow21 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIApplyWindow UIApplyWindow
        {
            get
            {
                if ((this.mUIApplyWindow == null))
                {
                    this.mUIApplyWindow = new UIApplyWindow(this);
                }
                return this.mUIApplyWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIApplyqueryWindow mUIApplyqueryWindow;
        
        private UIItemWindow3 mUIItemWindow;
        
        private UISeverityWindow mUISeverityWindow;
        
        private UIText1Window2 mUIText1Window;
        
        private UIAllWindow mUIAllWindow;
        
        private UISelectedclassesWindow mUISelectedclassesWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow21 mUIItemWindow2;
        
        private UIApplyWindow mUIApplyWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIApplyqueryWindow : WinWindow
    {
        
        public UIApplyqueryWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "29";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIApplyqueryCheckBox
        {
            get
            {
                if ((this.mUIApplyqueryCheckBox == null))
                {
                    this.mUIApplyqueryCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIApplyqueryCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Apply query";
                    this.mUIApplyqueryCheckBox.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIApplyqueryCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIApplyqueryCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "16";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinListItem UIView1ListItem
        {
            get
            {
                if ((this.mUIView1ListItem == null))
                {
                    this.mUIView1ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIView1ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "View 1";
                    this.mUIView1ListItem.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIView1ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIView1ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISeverityWindow : WinWindow
    {
        
        public UISeverityWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "25";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UISeverityRadioButton
        {
            get
            {
                if ((this.mUISeverityRadioButton == null))
                {
                    this.mUISeverityRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUISeverityRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Severity >=";
                    this.mUISeverityRadioButton.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUISeverityRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUISeverityRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window2 : WinWindow
    {
        
        public UIText1Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "22";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAllWindow : WinWindow
    {
        
        public UIAllWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "26";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIAllRadioButton
        {
            get
            {
                if ((this.mUIAllRadioButton == null))
                {
                    this.mUIAllRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIAllRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "All";
                    this.mUIAllRadioButton.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIAllRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIAllRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISelectedclassesWindow : WinWindow
    {
        
        public UISelectedclassesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "24";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UISelectedclassesRadioButton
        {
            get
            {
                if ((this.mUISelectedclassesRadioButton == null))
                {
                    this.mUISelectedclassesRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUISelectedclassesRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Selected classes";
                    this.mUISelectedclassesRadioButton.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUISelectedclassesRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUISelectedclassesRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "27";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinListItem UIDiscreteExtremeBrighListItem
        {
            get
            {
                if ((this.mUIDiscreteExtremeBrighListItem == null))
                {
                    this.mUIDiscreteExtremeBrighListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIDiscreteExtremeBrighListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Discrete Extreme Bright";
                    this.mUIDiscreteExtremeBrighListItem.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIDiscreteExtremeBrighListItem;
            }
        }
        
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIDiscreteExtremeBrighListItem;
        
        private WinList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "18";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinListItem UIItem1ListItem
        {
            get
            {
                if ((this.mUIItem1ListItem == null))
                {
                    this.mUIItem1ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIItem1ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "1";
                    this.mUIItem1ListItem.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIItem1ListItem;
            }
        }
        
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        
        public WinListItem UIItem4ListItem
        {
            get
            {
                if ((this.mUIItem4ListItem == null))
                {
                    this.mUIItem4ListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIItem4ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "4";
                    this.mUIItem4ListItem.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIItem4ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIItem1ListItem;
        
        private WinList mUIItemList;
        
        private WinListItem mUIItem4ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIApplyWindow : WinWindow
    {
        
        public UIApplyWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinButton UIApplyButton
        {
            get
            {
                if ((this.mUIApplyButton == null))
                {
                    this.mUIApplyButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIApplyButton.SearchProperties[WinButton.PropertyNames.Name] = "Apply";
                    this.mUIApplyButton.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIApplyButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIApplyButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Query Definition");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Query Definition");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow12 : WinWindow
    {
        
        public UIItemWindow12()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIClearAllMenuItem
        {
            get
            {
                if ((this.mUIClearAllMenuItem == null))
                {
                    this.mUIClearAllMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIClearAllMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Clear All";
                    #endregion
                }
                return this.mUIClearAllMenuItem;
            }
        }
        
        public WinMenuItem UISetAllMenuItem
        {
            get
            {
                if ((this.mUISetAllMenuItem == null))
                {
                    this.mUISetAllMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISetAllMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Set All";
                    #endregion
                }
                return this.mUISetAllMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIClearAllMenuItem;
        
        private WinMenuItem mUISetAllMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UILiveModeSettingsWindow : WinWindow
    {
        
        public UILiveModeSettingsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Live Mode Settings";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public UIStoponselectionWindow UIStoponselectionWindow
        {
            get
            {
                if ((this.mUIStoponselectionWindow == null))
                {
                    this.mUIStoponselectionWindow = new UIStoponselectionWindow(this);
                }
                return this.mUIStoponselectionWindow;
            }
        }
        
        public UIAutomaticallyresumelWindow UIAutomaticallyresumelWindow
        {
            get
            {
                if ((this.mUIAutomaticallyresumelWindow == null))
                {
                    this.mUIAutomaticallyresumelWindow = new UIAutomaticallyresumelWindow(this);
                }
                return this.mUIAutomaticallyresumelWindow;
            }
        }
        
        public UIText1Window3 UIText1Window
        {
            get
            {
                if ((this.mUIText1Window == null))
                {
                    this.mUIText1Window = new UIText1Window3(this);
                }
                return this.mUIText1Window;
            }
        }
        
        public UIText1Window11 UIText1Window1
        {
            get
            {
                if ((this.mUIText1Window1 == null))
                {
                    this.mUIText1Window1 = new UIText1Window11(this);
                }
                return this.mUIText1Window1;
            }
        }
        
        public UIDelaydefectdisplayWindow UIDelaydefectdisplayWindow
        {
            get
            {
                if ((this.mUIDelaydefectdisplayWindow == null))
                {
                    this.mUIDelaydefectdisplayWindow = new UIDelaydefectdisplayWindow(this);
                }
                return this.mUIDelaydefectdisplayWindow;
            }
        }
        
        public UIOption1Window UIOption1Window
        {
            get
            {
                if ((this.mUIOption1Window == null))
                {
                    this.mUIOption1Window = new UIOption1Window(this);
                }
                return this.mUIOption1Window;
            }
        }
        
        public UIText1Window21 UIText1Window2
        {
            get
            {
                if ((this.mUIText1Window2 == null))
                {
                    this.mUIText1Window2 = new UIText1Window21(this);
                }
                return this.mUIText1Window2;
            }
        }
        
        public UIOption1Window1 UIOption1Window1
        {
            get
            {
                if ((this.mUIOption1Window1 == null))
                {
                    this.mUIOption1Window1 = new UIOption1Window1(this);
                }
                return this.mUIOption1Window1;
            }
        }
        
        public UIText1Window31 UIText1Window3
        {
            get
            {
                if ((this.mUIText1Window3 == null))
                {
                    this.mUIText1Window3 = new UIText1Window31(this);
                }
                return this.mUIText1Window3;
            }
        }
        
        public UIDelayloadingnextinspWindow UIDelayloadingnextinspWindow
        {
            get
            {
                if ((this.mUIDelayloadingnextinspWindow == null))
                {
                    this.mUIDelayloadingnextinspWindow = new UIDelayloadingnextinspWindow(this);
                }
                return this.mUIDelayloadingnextinspWindow;
            }
        }
        
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIStoponselectionWindow mUIStoponselectionWindow;
        
        private UIAutomaticallyresumelWindow mUIAutomaticallyresumelWindow;
        
        private UIText1Window3 mUIText1Window;
        
        private UIText1Window11 mUIText1Window1;
        
        private UIDelaydefectdisplayWindow mUIDelaydefectdisplayWindow;
        
        private UIOption1Window mUIOption1Window;
        
        private UIText1Window21 mUIText1Window2;
        
        private UIOption1Window1 mUIOption1Window1;
        
        private UIText1Window31 mUIText1Window3;
        
        private UIDelayloadingnextinspWindow mUIDelayloadingnextinspWindow;
        
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIStoponselectionWindow : WinWindow
    {
        
        public UIStoponselectionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIStoponselectionCheckBox
        {
            get
            {
                if ((this.mUIStoponselectionCheckBox == null))
                {
                    this.mUIStoponselectionCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIStoponselectionCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Stop on selection";
                    this.mUIStoponselectionCheckBox.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIStoponselectionCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIStoponselectionCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAutomaticallyresumelWindow : WinWindow
    {
        
        public UIAutomaticallyresumelWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "13";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIAutomaticallyresumelCheckBox
        {
            get
            {
                if ((this.mUIAutomaticallyresumelCheckBox == null))
                {
                    this.mUIAutomaticallyresumelCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIAutomaticallyresumelCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Automatically resume live mode";
                    this.mUIAutomaticallyresumelCheckBox.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIAutomaticallyresumelCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIAutomaticallyresumelCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window3 : WinWindow
    {
        
        public UIText1Window3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "14";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window11 : WinWindow
    {
        
        public UIText1Window11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "11";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDelaydefectdisplayWindow : WinWindow
    {
        
        public UIDelaydefectdisplayWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIDelaydefectdisplayCheckBox
        {
            get
            {
                if ((this.mUIDelaydefectdisplayCheckBox == null))
                {
                    this.mUIDelaydefectdisplayCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIDelaydefectdisplayCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Delay defect display";
                    this.mUIDelaydefectdisplayCheckBox.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIDelaydefectdisplayCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIDelaydefectdisplayCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOption1Window : WinWindow
    {
        
        public UIOption1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "8";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIOption1RadioButton
        {
            get
            {
                if ((this.mUIOption1RadioButton == null))
                {
                    this.mUIOption1RadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIOption1RadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Option1";
                    this.mUIOption1RadioButton.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIOption1RadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIOption1RadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window21 : WinWindow
    {
        
        public UIText1Window21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "10";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOption1Window1 : WinWindow
    {
        
        public UIOption1Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIOption1RadioButton
        {
            get
            {
                if ((this.mUIOption1RadioButton == null))
                {
                    this.mUIOption1RadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIOption1RadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Option1";
                    this.mUIOption1RadioButton.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIOption1RadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIOption1RadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIText1Window31 : WinWindow
    {
        
        public UIText1Window31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "9";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDelayloadingnextinspWindow : WinWindow
    {
        
        public UIDelayloadingnextinspWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIDelayloadingnextinspCheckBox
        {
            get
            {
                if ((this.mUIDelayloadingnextinspCheckBox == null))
                {
                    this.mUIDelayloadingnextinspCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIDelayloadingnextinspCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Delay loading next inspection";
                    this.mUIDelayloadingnextinspCheckBox.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIDelayloadingnextinspCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIDelayloadingnextinspCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Live Mode Settings");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Live Mode Settings");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFeatureSelectionWindow : WinWindow
    {
        
        public UIFeatureSelectionWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Feature Selection";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ThunderRT6FormDC";
            this.WindowTitles.Add("Feature Selection");
            #endregion
        }
        
        #region Properties
        public UIItemWindow4 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow4(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow13 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow13(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow22 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow22(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIOKWindow2 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow2(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow4 mUIItemWindow;
        
        private UIItemWindow13 mUIItemWindow1;
        
        private UIItemWindow22 mUIItemWindow2;
        
        private UIOKWindow2 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "8";
            this.WindowTitles.Add("Feature Selection");
            #endregion
        }
        
        #region Properties
        public WinListItem UIDefectNoListItem
        {
            get
            {
                if ((this.mUIDefectNoListItem == null))
                {
                    this.mUIDefectNoListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIDefectNoListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Defect No.";
                    this.mUIDefectNoListItem.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIDefectNoListItem;
            }
        }
        
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        
        public WinListItem UIDownwebCenterListItem
        {
            get
            {
                if ((this.mUIDownwebCenterListItem == null))
                {
                    this.mUIDownwebCenterListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIDownwebCenterListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Downweb Center";
                    this.mUIDownwebCenterListItem.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIDownwebCenterListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIDefectNoListItem;
        
        private WinList mUIItemList;
        
        private WinListItem mUIDownwebCenterListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow13 : WinWindow
    {
        
        public UIItemWindow13(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Feature Selection");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow22 : WinWindow
    {
        
        public UIItemWindow22(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Feature Selection");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow2 : WinWindow
    {
        
        public UIOKWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "4";
            this.WindowTitles.Add("Feature Selection");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Feature Selection");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
